// Social-Cycling-Frontend_old/src/components/common/footer/Footer.jsx
import React from 'react';
import './footer.scss';

const Footer = () => {
    return (
        <footer className="footer">
            <div className="footer__container">
                <p>Copyright © {new Date().getFullYear()} {" "}
                    <a href="https://github.com/jensrott/Social-Cycling" target="blank">
                        Social Cycling
                    </a>
                </p>
            </div>
        </footer>
    )
}

export default Footer

// client/src/app/footer/footer.component.ts
import { Component } from '@angular/core';
import { MatToolbar } from "@angular/material/toolbar";

@Component({
  selector: 'app-footer',
  styleUrl: 'footer.component.scss',
  imports: [MatToolbar],
  template: `
<mat-toolbar class="footer">
    <p>Copyright {{currentYear}} ©
        <a href="https://github.com/jensrott/Social-Cycling" target="_blank">
            Social Cycling
        </a>
    </p>
</mat-toolbar>
`,
})
export class FooterComponent {
  public currentYear: number = new Date().getFullYear();
}
